Gemfile
Not sure if this should be in the Gemfile or in the Gemspec.
=> Added foreman client api gem.

bin/update
Fixed template in main here: https://github.com/ManageIQ/manageiq/pull/16777, needed to also for all the providers
=> Fixes bin/update typo

app/models/manageiq/providers/foreman/configuration_manager/refresher.rb, app/models/manageiq/providers/foreman/provisioning_manager/refresher.rb
Remove useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472
=> Remove useless EmsRefresherMixin

lib/manageiq/providers/foreman/engine.rb
See ManageIQ/manageiq-ui-classic#4496 for primary motivation.
=> Add plugin display name

spec/models/manageiq/providers/foreman/configuration_manager/configuration_profile_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager/configured_system/placement_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager/provision_workflow_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager/refresher_locations_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager/refresher_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager_spec.rb, spec/models/manageiq/providers/foreman/provider_spec.rb
This PR is a followup to ManageIQ/manageiq#18279 where we're updating FactoryGirl to FactoryBot.
=> Change FactoryGirl to FactoryBot

app/models/manageiq/providers/foreman/configuration_manager/provision_task/options_helper.rb
@agrare @jrafanie Please review.
=> Remove references to MiqPassword

lib/manageiq/providers/foreman/engine.rb
Change plugin common methods to class methods
=> Change plugin common methods to class methods

app/models/manageiq/providers/foreman/configuration_manager/refresh_worker.rb, app/models/manageiq/providers/foreman/provisioning_manager/refresh_worker.rb
Requires https://github.com/ManageIQ/manageiq/pull/19516
=> Rely on the default implementation of .ems_class

app/models/manageiq/providers/foreman/configuration_manager.rb, app/models/manageiq/providers/foreman/provisioning_manager.rb
just what it says on the tin
@miq-bot add_label cleanup
@miq-bot assign @agrare
=> remove rest of inventory object refresh

app/models/manageiq/providers/foreman/provider.rb
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277
=> Update DDF schema to version 2

app/models/manageiq/providers/foreman/provider.rb
This is to fix https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8755
Added translation for error message in provider validation
Issue:
=> Fix translation for provider validation message

.codeclimate.yml, .gitignore, .rubocop.yml, .rubocop_cc.yml, .travis.yml, README.md, Rakefile, bin/ci/after_script, config/settings.yml, lib/manageiq/providers/foreman/engine.rb, lib/tasks/README.md, lib/tasks_private/spec.rake, manageiq-providers-foreman.gemspec, spec/spec_helper.rb
=> Plugin Generator Updates

.codeclimate.yml, .rubocop.yml, .rubocop_cc.yml, manageiq-providers-foreman.gemspec
Depends on: https://github.com/ManageIQ/miq_bot/pull/506
=> Switch to manageiq-style

app/models/manageiq/providers/foreman/provider.rb
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7655
=> Update provider schema  with dataType

.gitignore, config/secrets.defaults.yml, lib/manageiq/providers/foreman/engine.rb, spec/models/manageiq/providers/foreman/configuration_manager/refresher_locations_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager/refresher_spec.rb, spec/spec_helper.rb
https://github.com/ManageIQ/manageiq/issues/21157
=> Use pluggable provider secrets

systemd/manageiq-providers-foreman_configuration_manager_refresh@.service
=> run services as manageiq user

app/models/manageiq/providers/foreman/configuration_manager.rb, app/models/manageiq/providers/foreman/provisioning_manager.rb
part of https://github.com/ManageIQ/manageiq/pull/21573
=> converting supported_for_create to supports :create

app/models/manageiq/providers/foreman/provider.rb
Continuing to remove uneeded memoization.
@miq-bot add-label bug
@miq-bot add-label najdorf/yes?
@miq-bot assign @agrare
=> Removing Memoization

app/models/manageiq/providers/foreman/configuration_manager/provision_task.rb
Related: https://github.com/ManageIQ/manageiq/pull/22552
=> Fix deliver_to_automate not taking any args

.gitignore, config/secrets.defaults.yml, lib/manageiq/providers/foreman/engine.rb, spec/config/secrets.defaults.yml, spec/models/manageiq/providers/foreman/configuration_manager/refresher_locations_spec.rb, spec/models/manageiq/providers/foreman/configuration_manager/refresher_spec.rb, spec/spec_helper.rb
=> Switch to use VcrSecrets helper from core

manageiq-providers-foreman.gemspec
=> Bump foreman_api_client to v1.1
