app/models/manageiq/providers/foreman/provider.rb
spec/models/manageiq/providers/foreman/provider_spec.rb

Manager name not updated on foreman provider edit
https://bugzilla.redhat.com/show_bug.cgi?id=1450457

Manager name not updated on foreman provider edit

---

spec/spec_helper.rb

Use the cassette_library_dir for foreman tests that use VCR
Cassettes for the `manageiq-provider-foreman` gem were still being referenced from `manageiq`
Allowing them to use their own local directory by uncommenting the `cassette_library_dir` VCR config setting.
Fixes https://github.com/ManageIQ/manageiq-providers-foreman/issues/6

Uncomment cassette_library_dir

---

app/models/manageiq/providers/foreman/configuration_manager.rb
app/models/manageiq/providers/foreman/configuration_manager/configured_system.rb

This is a continuation of the work started in https://github.com/ManageIQ/manageiq/pull/16596 where we want to migrate display model names from locale/en.yml into particular models, where we'll use standard gettext. Main goal here is to make this one aspect of our application pluggable.
Core PR: https://github.com/ManageIQ/manageiq/pull/16836

Migrate model display names from locale/en.yml to plugin

---

app/models/manageiq/providers/foreman/provider.rb
spec/models/manageiq/providers/foreman/provider_spec.rb

When validating against foreman provider with a closed TCP port, the connection timeout is higher than in Apache and instead of returning with the timeout issue, the server fails with a proxy error. The right solution would be to rewrite the provider validation to be asynchronous, however, with the current implementation it is not possible. There are people working on a complete rewrite of the add/edit provider forms but it's a lot of work and we need this fix ASAP.
I know this is a really ugly way to fix this problem, but the provider forms are far worse :cry: 
@miq-bot add_label gaprindashvili/yes, bug
@miq-bot add_reviewer @mzazrivec 
@miq-bot add_reviewer @martinpovolny 
https://bugzilla.redhat.com/show_bug.cgi?id=1564601

Add 100 seconds as connection timeout to return sooner than apache

---

app/models/manageiq/providers/foreman/provisioning_manager.rb

Disable creation of the provisioning manager for creation through the
UI/API as this is a "child" manager but doesn't have a parent_manager
because it belongs to a parent provider.  This is unique so we have to
handle this differently.

Disable UI/API support for creation

---

spec/models/manageiq/providers/foreman/provider_spec.rb

https://github.com/ManageIQ/manageiq/pull/19083 changed the foreman
provider factory to sequence the url which is causing spec failures.

Fix for new foreman factory url generation

---

app/models/manageiq/providers/foreman/configuration_manager.rb
app/models/manageiq/providers/foreman/provider.rb
app/models/manageiq/providers/foreman/provisioning_manager.rb

Add a method to return the needed parameters to add a foreman provider
and a method to verify credentials with these parametes.
https://github.com/ManageIQ/manageiq/issues/18818

Add params_for_create and verify_credentials

---

app/models/manageiq/providers/foreman/provider.rb
spec/models/manageiq/providers/foreman/provider_spec.rb

Currently you cannot create a Foreman provider in the maintenance zone. Instead, this should be legal, though with the provision and configuration managers disabled.
Similar to https://github.com/ManageIQ/manageiq/pull/19947

Foreman provider should allow creation in maintenance zone

---

app/models/manageiq/providers/foreman/configuration_manager.rb
app/models/manageiq/providers/foreman/provisioning_manager.rb
spec/models/manageiq/providers/foreman/configuration_manager_spec.rb

This will allow us to ask for the endpoints/authentications the same way through the API as we do with other providers.
@agrare should we also do this delegation in the prov manager?
Parent issues:
https://github.com/ManageIQ/manageiq/issues/18818
https://github.com/ManageIQ/manageiq/issues/19992

Delegate endpoints and authentications on managers to the provider

---

app/models/manageiq/providers/foreman/provider.rb

The DDF schema had to be adjusted to the DB schema field names, then the validation has been adjusted to pass again. On top of this I implemented the create and edit methods that can consume the data format produced by the forms.
**Old:**
*New:**
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818

Adjusted the DDF schema and validation

---

app/models/manageiq/providers/foreman/provider.rb

The DDF checkbox only supports a `true` value and when it's not checked, it doesn't even get submitted with the form. If the SSL verification checkbox value doesn't get submitted, the default value will kick in which makes impossible to set the verification to a `false` value. Instead of this, I am replacing it with a dropdown, that doesn't have this issue.
https://github.com/ManageIQ/manageiq/issues/18818
https://github.com/ManageIQ/manageiq-ui-classic/pull/7047
https://github.com/ManageIQ/manageiq-providers-foreman/pull/62#issuecomment-649437942

Replace SSL verification checkbox with a dropdown in the DDF

---

app/models/manageiq/providers/foreman/configuration_manager.rb

When autosaving the base provider relation we don't need to override
create_from_params and edit_with_params

Don't need to override create_from_params

---

app/models/manageiq/providers/foreman/provider.rb

The default behavior for the `async-credentials` component is [changing to be optional](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347), so it has to be explicitly marked as required here.

Make the default credentials required in the provider DDF

---

app/models/manageiq/providers/foreman/configuration_manager.rb
app/models/manageiq/providers/foreman/provider.rb
spec/models/manageiq/providers/foreman/configuration_manager/refresh_worker_spec.rb

Delegating the zone to the provider breaks the PerEmsWorkerMixin which does worker_class.where(:zone => zone) for all_ems_in_zone
Similiar issue as https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/239

Delegating zone to provider breaks worker_class.where

---

app/models/manageiq/providers/foreman/inventory/persister/foreman.rb

Set the parent in settings so it is picked up correctly for cross-manager refreshes
Fixes https://github.com/ManageIQ/manageiq-cross_repo-tests/runs/6598733995?check_suite_focus=true#step:6:2336
Depends on:
Required for:
* https://github.com/ManageIQ/manageiq/pull/21650

Use add_collection_for_manager to set parent properly

---

manageiq-providers-foreman.gemspec

apipie-bindings 0.4.0 was bumped as it added ruby 3 support, which dropped some URI methods such as decode/encode/escape/unescape.
See also https://github.com/ManageIQ/manageiq/pull/21036

Bump to foreman_api_client 1.0.2 for ruby 3 support

---

app/models/manageiq/providers/foreman/configuration_manager/refresh_worker.rb
app/models/manageiq/providers/foreman/provisioning_manager.rb
app/models/manageiq/providers/foreman/provisioning_manager/refresher.rb
config/settings.yml

This provider was missed during the changes for https://github.com/ManageIQ/manageiq/pull/20345 
Related: https://github.com/ManageIQ/manageiq/pull/22419
Dependent:
* https://github.com/ManageIQ/manageiq-schema/pull/685

Delegate Provisioning refresh to Configuration

---

lib/manageiq-providers-foreman.rb
lib/manageiq/providers/foreman.rb
spec/spec_helper.rb

Adopt convention already supported by bundler and required by zeitwerk so we don't need to tell zeitwerk to ignore this lib/gem-name.rb file.

Drop lib/gem-name.rb in favor of lib/gem/name.rb

---

app/models/manageiq/providers/foreman/configuration_manager.rb
app/models/manageiq/providers/foreman/configuration_manager/configured_system.rb
app/models/manageiq/providers/foreman/configuration_manager/provision_task.rb
app/models/manageiq/providers/foreman/configuration_manager/refresh_worker.rb
app/models/manageiq/providers/foreman/inventory.rb
app/models/manageiq/providers/foreman/inventory/collector.rb
app/models/manageiq/providers/foreman/inventory/parser.rb
app/models/manageiq/providers/foreman/inventory/persister.rb

Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854

Drop require_nested and include_concern

---

config/settings.yml

Reasoning here: https://github.com/ManageIQ/manageiq-providers-azure/pull/564#issuecomment-2445034651
- provisioning manager `refresh_ems` is already delegated to the configuration manager, the refresh just needs to be disabled
@miq-bot assign @agrare
@miq-bot add_label bug, radjabov/yes?
@miq-bot add_reviewer @agrare

Disable scheduled refresh for provision child manager
